Build Process Improvements - added silent option that gets rid of all std output messages
OnionIoT/openwrt-buildsystem-wrapper pull request #11
Opened 2023-04-10 18:56 UTC by greenbreakfast

@jempatel I've added a silent option that triggers the pipe to `/dev/null` in the `do_run` function.
I like the idea of being able to control the verbosity of the compile command as well as the output of any command run through `do_run`

Let me know what you think

2023-04-11 06:15 UTC, jempatel commented
> @jempatel I've added a silent option that triggers the pipe to `/dev/null` in the `do_run` function. I like the idea of being able to control the verbosity of the compile command as well as the output of any command run through `do_run`
> 
> Let me know what you think

Ah nice, That makes a lot of sense :)

2023-04-11 06:19 UTC, jempatel requested changes

2023-04-11 06:19 UTC, jempatel commented on build.sh
> +		s) SILENT=1;;
argument support needs to be added in getopts

```bash
while getopts m:v:c:o:AKdpCDXVsh OPT; do
```

2023-04-12 00:21 UTC, greenbreakfast commented on build.sh
> +		s) SILENT=1;;
Added to getopts

2023-04-12 00:22 UTC, greenbreakfast commented
@jempatel I've added `s` to the getopts command, thanks for the heads up.
I'm gonna merge this in, feel free to reopen the issue if needed.

2023-04-12 00:22 UTC, merged